name: Run Playwright Script

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install  # This should now work if package.json is in the root

    - name: Install Playwright dependencies
      run: npx playwright install-deps

    - name: Run Playwright Script
      run: node script.js  # Adjust as needed

