name: PR Branch Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is from release branch
      run: |
        if [[ "${{ github.head_ref }}" != "relese" ]]; then
          echo "Pull requests to main branch must come from the release branch.";
          exit 1;
        fi
