name: PR Branch Check

on:
  pull_request:
    branches:
      - release

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is from dev branch
      run: |
        if [[ "${{ github.head_ref }}" != "dev , hotfix*" ]]; then
          echo "Pull requests to release branch must come from the dev branch.";
          exit 1;
        fi
